<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'arsene' => [[], ['_controller' => 'App\\Controller\\ArseneController::home'], [], [['text', '/']], [], [], []],
    'plus' => [[], ['_controller' => 'App\\Controller\\ArseneController::about'], [], [['text', '/plus']], [], [], []],
    'ars1' => [[], ['_controller' => 'App\\Controller\\ArseneController::ars1'], [], [['text', '/ars1']], [], [], []],
    'ars2' => [[], ['_controller' => 'App\\Controller\\ArseneController::ars2'], [], [['text', '/ars2']], [], [], []],
    'ini' => [[], ['_controller' => 'App\\Controller\\ArseneController::ini'], [], [['text', '/ini']], [], [], []],
    'App\Controller\ArseneController::index' => [[], ['_controller' => 'App\\Controller\\ArseneController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\ArseneController::about' => [[], ['_controller' => 'App\\Controller\\ArseneController::about'], [], [['text', '/plus']], [], [], []],
    'App\Controller\ArseneController::ars1' => [[], ['_controller' => 'App\\Controller\\ArseneController::ars1'], [], [['text', '/ars1']], [], [], []],
    'App\Controller\ArseneController::ars2' => [[], ['_controller' => 'App\\Controller\\ArseneController::ars2'], [], [['text', '/ars2']], [], [], []],
    'App\Controller\ArseneController::ini' => [[], ['_controller' => 'App\\Controller\\ArseneController::ini'], [], [['text', '/ini']], [], [], []],
];
